name: call_video
description: A Flutter library with video calls
repository: https://github.com/thinhtientech/vkyc-flutter-sdk/blob/main/lib/call_video.dart
issue_tracker: https://github.com/thinhtientech/vkyc-flutter-sdk/issues
version: 1.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=2.5.0'


dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.8.0
  permission_handler: ^10.4.3
  agora_rtc_engine: ^6.2.1
  stomp_dart_client: ^0.4.4
  dio: ^5.3.1
  path_provider: ^2.0.15
  device_info_plus: ^9.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  json_serializable: ^6.6.1
  build_runner: ^2.3.3


flutter:
  uses-material-design: true

